env:
    CIRRUS_CLONE_DEPTH: 1
    
task:
    name: aosp build
    timeout_in: 120m 
    container:
      image: apon77/aosp:latest
      cpu: 16
      memory: 80G
    build_script: 
      - chmod +x build.sh
      - ./build.sh
